### ISSUE TITLE
Update collecion

### ISSUE THREAD

**Issue by rafaelbotelhoetibr** [esendir/MongoRepository#11]
Hello.
I  have using the MongoRepository and I a question that I hope you can help me.

I have the following situation:

Entity:
`{
  Id: 0,
  Name: 'Sample'
  Collection: [
    {
      Id: 0
      Status: 0
    },
    {
      Id: 1
      Status: 0
    },
    {
      Id: 2
      Status: 0
    }
  ]
}`

Is possible to do a update the Status for all collection items without get them, to update out of database and after to do a update each one?

I believe is possible using UpdateDefinition, but I don't know how use.

Could you help me with this question?

**Comment by esendir** [comment]
Hi @rafaelbotelho 
Unfortunately there is no set function for that, either you set it with a string representation of the tree and $ sign; e.g "Collection.$.Status" 
or
you can use below function in your repository to update the status of all items in collection and then replace in database.

> public void UpdateAllStatus(MyEntity entity, int newStatus)
> {
>       entity.Collection.ForEach(i => i.Status = newStatus);
>       Replace(entity);
> }

Good luck
