### ISSUE TITLE
Services Layer Or Extended Repository

### ISSUE THREAD

**Issue by Vikaskumargd** [esendir/MongoRepository#12]
Hi Usame,
I need some help regarding the use of Services Layer and extended Repository using MongoRepository. I am very confused b/w using services and extended Repository in Web Api controller. I am not sure which one use and I also trying unit testing. So Usame can you guide me with this .
I know this place(Issue Section ) is not for this kind of problem but for me there was no other way to contact you.
Thanks 
![untitled drawing](https://cloud.githubusercontent.com/assets/7469181/25784276/73b4e738-3387-11e7-85a5-653ab31b6b77.jpg)

**Comment by Vikaskumargd** [comment]
I also have one approach of having generic repository object in services

**Comment by esendir** [comment]
Sorry for late reply, although this not an issue about the library, I would prefer left one.
In repository, it is good to have simple methods which handles only single data read or write.
But in most of the post API, you may need multiple read or writes for one call, where you can manage them via service layer.

**Comment by Vikaskumargd** [comment]
Thanks @esendir.
