### ISSUE TITLE
Get attribute name issue

### ISSUE THREAD

**Issue by leakeyash** [esendir/MongoRepository#14]
The method `GetCollectionNameFromType` in Database class.

Why not use 
`typeof(T).GetCustomAttribute<CollectionNameAttribute>(true)`
but you are using
`typeof(T).GetTypeInfo().Assembly.GetCustomAttribute<CollectionNameAttribute>()`?

Is this correct to get the attribute value?

**Comment by esendir** [comment]
It is because of .netstandard support, GetCustomAttribute method is not available for .netstandard1.5
