### ISSUE TITLE
Better to have push function to update arrays

### ISSUE THREAD

**Issue by leakeyash** [esendir/MongoRepository#15]
There are some requirements to update arrays such as add, without push functions we have to update the whole array?

**Comment by esendir** [comment]
There are many update features like push, pop, pull, combine, rename, set, etc.
You can access them via Updater object in the repository.
In the readme sample is available for set method, for push you can use below sample

```csharp
item = new Item(); 
var update = Updater.Push(i => i.Items, item); 
repo.Update(item, update);
```
