### ISSUE TITLE
Working with expressions

### ISSUE THREAD

**Issue by jigneshkvp** [esendir/MongoRepository#18]
Hello @esendir ,

I am unable to use expression in Find or FindAll queries, if they are built using System.Linq.Expressions.

E.g. If I use a predicate builder to build a search query based on request pararmeters then the code throws an exception saying "Unsupported query...".

Also how to filter by dates?

Could you please help by providing an example of how to make it work using expressions?

**Comment by jigneshkvp** [comment]
Not an issue. I had issues with the way I initialized repo.

E.g. I had the entity object name as "LogDbDto"  and the collection name that I specified on it was "Logs".
This is how I initialized my repo:
`var logRepo = new Repository<LogDbDto>(connectionString);`

so by default the collection name it considered was "logdbdto" and created a new collection in MongoDb.

Issue: It didn't use the "CollectionName("Logs")" that I specified on the Entity object. Strange!!

Solution: I initialized like this : `var logRepo = new Repository<LogDbDto>(connectionString, "Logs");` and then it worked

**Comment by esendir** [comment]
Hello @jigneshkvp 

Unfortunately mongo library does not support all linq queries, specially with dates.
Will check the attribute issue

Thanks

**Comment by esendir** [comment]
Attribute is fixed

**Comment by jigneshkvp** [comment]
Thanks @esendir !
