### ISSUE TITLE
Expensive contructor

### ISSUE THREAD

**Issue by Dan-True** [esendir/MongoRepository#23]
Hello

I am using your fine library for a customer who has a very performance-sensitive API. Even a few milliseconds overhead is a problem for their SLA. Most database calls are behind a memory cache layer for the same reason.

Looking at the code, constructing a repository class seems to take somewhere between 40-120 milliseconds (in debug build) and even has a noticeable effect on the RPM of the release version, even when the actual calls are usually never executed because of the memory cache layer.

This is not a problem for us, as we will just wait to construct the repository until we actually need it (i.e. after a cache miss). But looking at your code the repository constructor only sets up the mongodb collection - which as far as I know should **not** establish a connection to the DB. But what else could cause this delay of that many milliseconds?

As I said, not really an issue, but in general constructors should be cheap and fast to execute - do you have a guess as to what could be responsible?

**Comment by esendir** [comment]
thanks for sharing the issue, it has been fixed now

**Comment by Dan-True** [comment]
Thank you.

On an unrelated note, I have a local version of the code where I've added support for multi-document transactions if you pass the constructor a session handle. Are you interested in pull requests?

Regards
   Dan

**Comment by esendir** [comment]
Worth to check, why not. 
We can discuss over the pull request.

**Comment by Dan-True** [comment]
Ok. I'm haivng some issues with the unit tests, as they fail on latest version on my machine.

Will make a pull request when I have that sorted.
